Models/Cd.cs
using System.ComponentModel.DataAnnotations;

namespace dt191g_moment32.Models;

public class Cd
{
    public int CdId { get; set; }
    
    [Required(ErrorMessage = "Ange en titel")]
    [Display(Name = "Titel")]
    public string? Title { get; set; }
    
    [Required(ErrorMessage = "Ange en genre")]
    public string? Genre { get; set; }
  
    [Required(ErrorMessage = "Ange minuter")]
    [Display(Name = "Speltid (minuter)")]
    public int Playtime { get; set; }

    [Required]
    [Display(Name = "Artist")]
    public int ArtistId { get; set; }
    public Artist? Artist { get; set; }
    
    public Loan? Loan { get; set; }
}

Controllers/CdController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dt191g_moment32.Data;
using dt191g_moment32.Models;

namespace dt191g_moment32.Controllers
{
    public class CdController : Controller
    {
        private readonly CollectionContext _context;

        public CdController(CollectionContext context)
        {
            _context = context;
        }

        // GET: Cd
        public async Task<IActionResult> Index(string searchString)
        {
            var collectionContext = _context.Cd.Include(c => c.Artist).Include(c => c.Loan);
            await _context.Artist.ToListAsync();
            
            var cds = from m in _context.Cd
                select m;
            
            if (!String.IsNullOrEmpty(searchString))
            {
                cds = cds.Where(s => s.Title!.ToLower().Contains(searchString.ToLower()));
                return View(await cds.ToListAsync());
            }

            return View(await collectionContext.ToListAsync());
        }

        // GET: Cd/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cd = await _context.Cd
                .Include(c => c.Artist)
                .FirstOrDefaultAsync(m => m.CdId == id);
            if (cd == null)
            {
                return NotFound();
            }

            return View(cd);
        }

        // GET: Cd/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name");
            return View();
        }

        // POST: Cd/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CdId,Title,Genre,Playtime,ArtistId")] Cd cd)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cd);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name", cd.ArtistId);
            return View(cd);
        }

        // GET: Cd/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cd = await _context.Cd.FindAsync(id);
            if (cd == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name", cd.ArtistId);
            return View(cd);
        }

        // POST: Cd/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CdId,Title,Genre,Playtime,ArtistId")] Cd cd)
        {
            if (id != cd.CdId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cd);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CdExists(cd.CdId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "Name", cd.ArtistId);
            return View(cd);
        }

        // GET: Cd/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cd = await _context.Cd
                .Include(c => c.Artist)
                .FirstOrDefaultAsync(m => m.CdId == id);
            if (cd == null)
            {
                return NotFound();
            }

            return View(cd);
        }

        // POST: Cd/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cd = await _context.Cd.FindAsync(id);
            _context.Cd.Remove(cd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CdExists(int id)
        {
            return _context.Cd.Any(e => e.CdId == id);
        }
    }
}

Views/Cd/Create.cshtml
@model dt191g_moment32.Models.Cd

@{
    ViewData["Title"] = "Ny CD";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ny CD</h2>

<h3>Cd</h3>
<div>
    <div>
        <form asp-action="Create" class="add-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Playtime" class="control-label"></label>
                <input asp-for="Playtime" class="form-control" />
                <span asp-validation-for="Playtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class ="form-control" asp-items="ViewBag.ArtistId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Skapa" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="link" asp-action="Index">Tillbaka</a>
</div>


Views/Cd/Delete.cshtml
@model dt191g_moment32.Models.Cd

@{
    ViewData["Title"] = "Radera";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Radera</h2>

<h3 class="border-bottom">Är du säker på att du vill radera CD-skivan?</h3>
<div>
    <h4>Cd</h4>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Playtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Playtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete" class="border-top">
        <input type="hidden" asp-for="CdId" />
        <span class="link delete-wrapper"><input type="submit" value="Radera" class="btn-delete" /></span> |
        <a class="link" asp-action="Index">Tillbaka</a>
    </form>
</div>

Views/Cd/Details.cshtml
@model dt191g_moment32.Models.Cd

@{
    ViewData["Title"] = "Detaljer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detaljer</h2>

<div>
    <h3 class="border-bottom">Cd</h3>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Playtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Playtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
    </dl>
</div>
<div class="border-top">
    <a class="link link-edit" asp-action="Edit" asp-route-id="@Model?.CdId">Redigera</a> |
    <a class="link" asp-action="Index">Tillbaka</a>
</div>

Views/Cd/Edit.cshtml
@model dt191g_moment32.Models.Cd

@{
    ViewData["Title"] = "Redigera";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Redigera</h2>

<h3>Cd</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" class="edit-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CdId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Playtime" class="control-label"></label>
                <input asp-for="Playtime" class="form-control" />
                <span asp-validation-for="Playtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="link" asp-action="Index">Tillbaka</a>
</div>


Views/Cd/Index.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model IEnumerable<dt191g_moment32.Models.Cd>

@{
    ViewData["Title"] = "CD-skivor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CD-skivor</h2>

<div>
    <a class="btn add-btn" asp-action="Create">Ny CD <i class="fa-solid fa-music"></i></a>
</div>

<form asp-controller="Cd" asp-action="Index" method="get" class="form-search">
    <div>
        Sök titel: <input type="text" name="SearchString" id="search-box"/>
        <div class="btn-container flex">
            <input class="btn-submit" type="submit" value="Sök" />
            <a class="btn-filter" asp-controller="Cd" asp-action="Index">Visa alla</a>
        </div>
    </div>
</form>

<table class="table cd-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Playtime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Playtime)
                 min
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist.Name)
            </td>
            <td>
                @{
                    if (item.Loan != null)
                    {
                       @:Utlånad 
                    }
                    else
                    {
                        @:Ledig
                    }
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CdId">Redigera</a> |
                <a asp-action="Details" asp-route-id="@item.CdId">Detaljer</a> |
                <a asp-action="Delete" asp-route-id="@item.CdId">Radera</a>
            </td>
        </tr>
}
    </tbody>
</table>